[package]
name = "boxit"
version = "0.1.0"
edition = "2024"

[dependencies]
aead-stream = { version = "0.6", features = ["alloc"] }
argon2 = "0.5"
chacha20poly1305 = "0.11"
rand = "0.9"
zeroize = { version = "1", features = ["zeroize_derive"] }

[dev-dependencies]
proptest = "1"

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "z" # Optimize for binary size
strip = true # Remove debug symbols
